when:
  branch:
    exclude: pages

steps:
  build:
    image: node:20
    commands:
      - npm ci
      - npm run build

  publish:
    image: bitnami/git
    secrets: [codeberg_token, mail]
    commands:
      - git config --global user.email "$${MAIL}"
      - git config --global user.name "Woodpecker CI"
      - git clone --branch pages https://$${CODEBERG_TOKEN}@codeberg.org/$CI_REPO.git _pages || git clone https://$${CODEBERG_TOKEN}@codeberg.org/$CI_REPO.git _pages && cd _pages && git checkout --orphan pages && cd ..
      - cd _pages
      - git rm -rf . || true
      - cp -ar ../dist/. .
      - git add .
      - git commit -m "Deploy: $CI_COMMIT_SHA" || echo "Nothing to deploy"
      - git push --set-upstream origin pages
